config/routes.rb
FatFreeCRM::Application.routes.draw do

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'options'    => 'home#options'
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup
  match 'timeline'   => 'home#timeline',           :as => :timeline
  match 'timezone'   => 'home#timezone',           :as => :timezone
  match 'toggle'     => 'home#toggle'

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts do
    collection do
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put :attach
      post :discard
    end
  end

  resources :campaigns do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :contacts do
    collection do
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :leads do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      get  :convert
      post :discard
      put  :attach
      put  :promote
      put  :reject
    end
  end

  resources :opportunities do
    collection do
      get  :filter
      get  :options
      get  :search
      post :auto_complete
      post :redraw
    end
    member do
      put  :attach
      post :discard
    end
  end

  resources :tasks do
    collection do
      get  :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get  :search
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :settings
    resources :plugins
  end

  match '/:controller(/:action(/:id))'
end

app/controllers/accounts_controller.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class AccountsController < ApplicationController
  before_filter :require_user
  before_filter :get_data_for_sidebar, :only => :index
  before_filter :set_current_tab, :only => [ :index, :show ]
  after_filter  :update_recently_viewed, :only => :show

  # GET /accounts
  # GET /accounts.xml                                             HTML and AJAX
  #----------------------------------------------------------------------------
  def index
    @accounts = get_accounts(:page => params[:page])

    respond_to do |format|
      format.html # index.html.haml
      format.js   # index.js.rjs
      format.xml  { render :xml => @accounts }
      format.xls  { send_data @accounts.to_xls, :type => :xls }
      format.csv  { send_data @accounts.to_csv, :type => :csv }
      format.rss  { render "common/index.rss.builder" }
      format.atom { render "common/index.atom.builder" }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.xml                                                    HTML
  #----------------------------------------------------------------------------
  def show
    @account = Account.my.find(params[:id])
    @stage = Setting.unroll(:opportunity_stage)
    @comment = Comment.new

    @timeline = Timeline.find(@account)

    respond_to do |format|
      format.html # show.html.haml
      format.xml  { render :xml => @account }
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:html, :xml)
  end

  # GET /accounts/new
  # GET /accounts/new.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def new
    @account = Account.new(:user => @current_user, :access => Setting.default_access)
    @users = User.except(@current_user)
    if params[:related]
      model, id = params[:related].split("_")
      instance_variable_set("@#{model}", model.classify.constantize.find(id))
    end

    respond_to do |format|
      format.js   # new.js.rjs
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/1/edit                                                   AJAX
  #----------------------------------------------------------------------------
  def edit
    @account = Account.my.find(params[:id])
    @users = User.except(@current_user)
    if params[:previous].to_s =~ /(\d+)\z/
      @previous = Account.my.find($1)
    end

  rescue ActiveRecord::RecordNotFound
    @previous ||= $1.to_i
    respond_to_not_found(:js) unless @account
  end

  # POST /accounts
  # POST /accounts.xml                                                     AJAX
  #----------------------------------------------------------------------------
  def create
    @account = Account.new(params[:account])
    @users = User.except(@current_user)

    respond_to do |format|
      if @account.save_with_permissions(params[:users])
        # None: account can only be created from the Accounts index page, so we
        # don't have to check whether we're on the index page.
        @accounts = get_accounts
        get_data_for_sidebar
        format.js   # create.js.rjs
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.js   # create.js.rjs
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml                                                    AJAX
  #----------------------------------------------------------------------------
  def update
    @account = Account.my.find(params[:id])

    respond_to do |format|
      if @account.update_with_permissions(params[:account], params[:users])
        get_data_for_sidebar
        format.js
        format.xml  { head :ok }
      else
        @users = User.except(@current_user) # Need it to redraw [Edit Account] form.
        format.js
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml)
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.xml                                        HTML and AJAX
  #----------------------------------------------------------------------------
  def destroy
    @account = Account.my.find(params[:id])
    @account.destroy if @account

    respond_to do |format|
      format.html { respond_to_destroy(:html) }
      format.js   { respond_to_destroy(:ajax) }
      format.xml  { head :ok }
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:html, :js, :xml)
  end

  # GET /accounts/search/query                                             AJAX
  #----------------------------------------------------------------------------
  def search
    @accounts = get_accounts(:query => params[:query], :page => 1)

    respond_to do |format|
      format.js   { render :index }
      format.xml  { render :xml => @accounts.to_xml }
    end
  end

  # PUT /accounts/1/attach
  # PUT /accounts/1/attach.xml                                             AJAX
  #----------------------------------------------------------------------------
  # Handled by ApplicationController :attach

  # PUT /accounts/1/discard
  # PUT /accounts/1/discard.xml                                            AJAX
  #----------------------------------------------------------------------------
  # Handled by ApplicationController :discard

  # POST /accounts/auto_complete/query                                     AJAX
  #----------------------------------------------------------------------------
  # Handled by ApplicationController :auto_complete

  # GET /accounts/options                                                  AJAX
  #----------------------------------------------------------------------------
  def options
    unless params[:cancel].true?
      @per_page = @current_user.pref[:accounts_per_page] || Account.per_page
      @outline  = @current_user.pref[:accounts_outline]  || Account.outline
      @sort_by  = @current_user.pref[:accounts_sort_by]  || Account.sort_by
    end
  end

  # POST /accounts/redraw                                                  AJAX
  #----------------------------------------------------------------------------
  def redraw
    @current_user.pref[:accounts_per_page] = params[:per_page] if params[:per_page]
    @current_user.pref[:accounts_outline]  = params[:outline]  if params[:outline]
    @current_user.pref[:accounts_sort_by]  = Account::sort_by_map[params[:sort_by]] if params[:sort_by]
    @accounts = get_accounts(:page => 1)
    render :index
  end

  # GET /accounts/contacts                                                 AJAX
  #----------------------------------------------------------------------------
  def contacts
    @account = Account.my.find(params[:id])
  end

  # GET /accounts/opportunities                                            AJAX
  #----------------------------------------------------------------------------
  def opportunities
    @account = Account.my.find(params[:id])
  end

  # POST /accounts/filter                                                  AJAX
  #----------------------------------------------------------------------------
  def filter
    session[:filter_by_account_category] = params[:category]
    @accounts = get_accounts(:page => 1)
    render :index
  end

  private
  #----------------------------------------------------------------------------
  def get_accounts(options = {})
    get_list_of_records(Account, options.merge!(:filter => :filter_by_account_category))
  end

  #----------------------------------------------------------------------------
  def respond_to_destroy(method)
    if method == :ajax
      @accounts = get_accounts
      get_data_for_sidebar
      if @accounts.blank?
        @accounts = get_accounts(:page => current_page - 1) if current_page > 1
        render :index and return
      end
      # At this point render default destroy.js.rjs template.
    else # :html request
      self.current_page = 1 # Reset current page to 1 to make sure it stays valid.
      flash[:notice] = "#{t(:asset_deleted, @account.name)}"
      redirect_to accounts_path
    end
  end

  #----------------------------------------------------------------------------
  def get_data_for_sidebar
    @account_category_total = Hash[
      Setting.account_category.map do |key|
        [ key, Account.my.where(:category => key.to_s).count ]
      end
    ]
    categorized = @account_category_total.values.sum
    @account_category_total[:all] = Account.my.count
    @account_category_total[:other] = @account_category_total[:all] - categorized
  end
end

app/helpers/accounts_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module AccountsHelper

  # Sidebar checkbox control for filtering accounts by category.
  #----------------------------------------------------------------------------
  def account_category_checbox(category, count)
    checked = (session[:filter_by_account_category] ? session[:filter_by_account_category].split(",").include?(category.to_s) : count.to_i > 0)
    onclick = remote_function(
      :url      => { :action => :filter },
      :with     => h(%Q/"category=" + $$("input[name='category[]']").findAll(function (el) { return el.checked }).pluck("value")/),
      :loading  => "$('loading').show()",
      :complete => "$('loading').hide()"
    )
    check_box_tag("category[]", category, checked, :id => category, :onclick => onclick)
  end

  # Quick account summary for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def account_summary(account)
    [ number_to_currency(account.opportunities.pipeline.map(&:weighted_amount).sum, :precision => 0),
      t(:added_by, :time_ago => time_ago_in_words(account.created_at), :user => account.user_id_full_name),
      t('pluralize.contact', account.contacts.count),
      t('pluralize.opportunity', account.opportunities.count),
      t('pluralize.comment', account.comments.count)
    ].join(', ')
  end
end

app/views/accounts/_account.html.haml
- amount = account.opportunities.pipeline.map(&:weighted_amount).sum
%li[account]{ highlightable(dom_id(account, :tools)) }
  - if account.category
    .strip{:class => account.category} #{t(account.category)}
  - else
    .strip{:style => "color: gray;"} #{t :other}

  .tools{ invisible, :id => dom_id(account, :tools) }
    = hook(:account_tools_before, self, :account => account)
    = link_to_edit(account) + " | "
    = link_to_delete(account)

  .indent
    = link_to(h(account.name), account)
    - if amount != 0.0
      %span.amount= number_to_currency(amount, :precision => 0)
    &ndash;
    %tt
      = account.location << ", " unless account.location.blank?
      = t(:added_by, :time_ago => time_ago_in_words(account.created_at), :user => (account.user.id == @current_user.id ? t(:me) : h(account.user.full_name))) << " | "
      = t('pluralize.contact', account.contacts.count) << " | "
      = t('pluralize.opportunity', account.opportunities.count)


    - unless @current_user.preference[:accounts_outline] == "brief"
      %dt
        = stars_for(account) + " | "
        = link_to(account.website, account.website.to_url) << " | " if account.website.present?
        = link_to_email(account.email) << " | " if account.email.present?
        = t(:phone_small) << ": " << (account.toll_free_phone || account.phone) if account.toll_free_phone? || account.phone?
      = hook(:account_bottom, self, :account => account)

app/views/accounts/_contact_info.html.haml
- edit ||= false
- collapsed = (@account.errors.empty? && session[:account_contact].nil?)
= subtitle :account_contact, collapsed, t(:contact_info)
.section
  %small#account_contact_intro{ hidden_if(!collapsed) }
    = t(:intro, t(:account_small)) unless edit
  #account_contact{ hidden_if(collapsed) }
    %table
      %tr
        %td{ :colspan => 3 }
          %table{ :width => "100%", :cellpadding => 0, :cellspacing => 0 }
            %tr
              %td
                .label #{t :phone_toll_free}:
                = f.text_field :toll_free_phone, :style => "width:154px"
              %td= spacer
              %td
                .label #{t :phone}:
                = f.text_field :phone, :style => "width:154px"
              %td= spacer
              %td
                .label #{t :fax}:
                = f.text_field :fax, :style => "width:154px"
      %tr
        %td
          .label.top #{t :website}:
          = f.text_field :website
        %td= spacer
        %td
          .label.top Email:
          = f.text_field :email
      %tr
        %td
          = render "common/address", :f => f, :asset => @account, :type => :billing, :title => :billing_address
        %td= spacer
        %td
          = render "common/address", :f => f, :asset => @account, :type => :shipping, :title => :shipping_address, :same_as_billing => true

app/views/accounts/_create.html.haml
= form_for(@account, :html => one_submit_only(:account), :remote => true) do |f|
  = link_to_close new_account_path
  = f.hidden_field :user_id

  = f.error_messages :object_name => t('account')

  = render "accounts/top_section",  :f => f
  = render "accounts/contact_info", :f => f
  = render "accounts/permissions",  :f => f
  .buttonbar
    - if Setting.compound_address
      = f.submit t(:create_account), :onclick => "crm.clear_all_hints()"
    - else
      = f.submit t(:create_account)
    #{t :or}
    = link_to_cancel new_account_path

app/views/accounts/_edit.html.haml
.remote
  = form_for(@account, :html => one_submit_only(:account), :remote => true) do |f|
    = link_to_close edit_account_path(@account)
    = f.hidden_field :user_id

    = f.error_messages :object_name => t('account')

    = render "accounts/top_section",  :f => f, :edit => true
    = render "accounts/contact_info", :f => f, :edit => true
    = render "accounts/permissions",  :f => f, :edit => true

    .buttonbar
      - if Setting.compound_address
        = f.submit t(:save_account), :onclick => "crm.clear_all_hints()"
      - else
        = f.submit t(:save_account)
      #{t :or}
      = link_to_cancel edit_account_path(@account)

app/views/accounts/_options.html.haml
%p
  = link_to_close options_accounts_path
  = hidden_field_tag "account[user_id]", @current_user.id

  - current_sort_by = t("option_" + Account.sort_by_map.invert[@sort_by])
  - current_outline = t("option_#{@outline}")
  - current_naming  = t("option_#{@naming}")

  -# sort_by: Sort {{models}} by {{field}}.
  = t(:sort_by, :models => t(:accounts_small), :field => link_to(current_sort_by, "#", :id => :sort_by)).html_safe

  -# show_per_page: Show {{number}} {{models}} per page using {{fmt}} format.
  = t(:show_per_page, :number => link_to(@per_page, "#", :id => :per_page), :models => t(:accounts_small), :fmt => link_to(current_outline, "#", :id => :outline)).html_safe

%p

%script
  = render "common/sort_by"
  = render "common/per_page"
  = render "common/outline"

app/views/accounts/_permissions.html.haml
- edit ||= false
- collapsed = session[:account_permissions].nil? # && @account.errors.empty?
= subtitle :account_permissions, collapsed, t(:permissions)
.section
  %small#account_permissions_intro{ hidden_if(!collapsed) }
    = get_default_permissions_intro(@account.access, t(:account_small)) unless edit
  #account_permissions{ hidden_if(collapsed) }
    .radio_box
      = f.radio_button :access, "Private", :onclick => "$('people').hide()"
      = label "account[access]", :private, t(:keep_private), :style => "cursor:pointer"
    .radio_box
      = f.radio_button :access, "Public", :onclick => "$('people').hide()"
      = label "account[access]", :public, t(:make_public), :style => "cursor:pointer"
    .radio_box
      = f.radio_button :access, "Shared", :onclick => "$('people').show()"
      = label "account[access]", :shared, t(:share_with), :style => "cursor:pointer"

    #people{ hidden_if(@account.access != "Shared") }
      %div{ :style => "padding: 6px 0px 0px 20px" }
        - for user in @users
          .check_box
            -# Preserve state of the checkboxes if the form gets redrawn on errors.
            = check_box_tag "users[]", user.id, @account.permissions.map(&:user_id).include?(user.id) || (params[:users] && params[:users].include?(user.id.to_s)), :id => "user_#{user.id}"
            = label_tag "user_#{user.id}", h(user.full_name), :style => "cursor:pointer"

app/views/accounts/_sidebar_index.html.haml
.filters#filters
  = render "common/search"
  = hook(:index_account_sidebar_bottom, self)
  - Setting.account_category.each do |key|
    .check_box{:style => "border-bottom: 1px silver dotted;"}
      %div{:style => "float:right;"}
        = @account_category_total[key]
      = account_category_checbox(key, @account_category_total[key])
      = label_tag(key, t(key))

  .check_box{:style => "border-bottom: 1px silver dotted;"}
    %div{:style => "float:right;"}
      = @account_category_total[:other]
    = account_category_checbox("other", @account_category_total[:other])
    = label_tag(:other, t(:other))

  .check_box
    %div{:style => "float:right;"}
      %b= @account_category_total[:all]
    %b #{t :total_accounts}
  = hook(:index_account_sidebar_bottom, self)

app/views/accounts/_sidebar_show.html.haml
- won = @account.opportunities.won.map(&:amount).sum
- lost = @account.opportunities.lost.map(&:amount).sum
- pipeline = @account.opportunities.pipeline.map(&:weighted_amount).sum

.panel#summary
  %h4= h(@account.name)
  - if @account.website
    %div
      %b= link_to(truncate(@account.website, :length => 30), @account.website.to_url, :"data-popup" => true, :title => t(:open_in_window, @account.website))
  - if @account.email.present?
    %div
      %b= link_to_email(@account.email, 30)

  %div
    - if @account.toll_free_phone
      #{t :phone_toll_free}: <b>#{@account.toll_free_phone}</b><br />

    - if @account.phone
      #{t :phone}: <b>#{@account.phone}</b><br />

    - if @account.fax
      #{t :fax}: <b>#{@account.fax}</b><br />

  %div= render "common/address_show", :asset => @account, :type => 'billing', :title => :billing_address
  %div= render "common/address_show", :asset => @account, :type => 'shipping', :title => :shipping_address

  .caption #{t :account_summary}
  %li
    %dt= pipeline != 0.0 ? number_to_currency(pipeline, :precision => 0) : t(:n_a)
    %tt #{t :pipeline}:
  %li
    %dt= won != 0.0 ? number_to_currency(won, :precision => 0) : t(:n_a)
    %tt #{t :won}:
  %li
    %dt= lost != 0.0 ? number_to_currency(lost, :precision => 0) : t(:n_a)
    %tt #{t :lost}:
  %li
    %dt= t(@account.category, :default => :other)
    %tt #{t :category}:
  %li
    %span{:style => "float:right;"}= stars_for(@account)
    %tt #{t :rating}:
  %li.last
    %dt= truncate((@account.assigned_to ? @account.assignee.full_name : @account.user.full_name), :length => 16)
    %tt #{t :assigned_to}:

  - unless @account.background_info.blank?
    .caption #{t :background_info}
    = auto_link(simple_format h(@account.background_info))

  = hook(:show_account_sidebar_bottom, self, :account => @account)

app/views/accounts/_top_section.html.haml
= hook(:account_top_section, self, :f => f) do
  .section
    %table
      %tr
        %td(colspan="5")
          .label.top.req #{t :name}:
          = f.text_field :name, :style => "width:500px"
      %tr
        %td
          .label #{t :assigned_to}:
          = collection_select :account, :assigned_to, @users, :id, :full_name, { :include_blank => t(:myself) }, { :style => "width:160px" }
        %td= spacer
        %td
          .label #{t :category}:
          = f.select :category, Setting.unroll(:account_category), { :selected => (@account.category || "other").to_sym, :include_blank => t(:other) }, { :style => "width:160px" }
        %td= spacer
        %td
          .label #{t :rating}:
          = rating_select "account[rating]", { :id => :account_rating, :selected => @account.rating, :style => "width:160px" }

      - if Setting.background_info && Setting.background_info.include?(:account)
        %tr
          %td(colspan="5")
            .label= t(:background_info) << ':'
            = f.text_area :background_info, :style =>"width:500px", :rows => 3

      = hook(:account_top_section_bottom, self, :f => f)

app/views/accounts/index.html.haml
= styles_for :account

.title_tools
  = link_to_inline(:create_account, new_account_path, :text => t(:create_account)) << " | "
  = link_to_inline(:options, options_accounts_path, :text=> t(:options))

.title
  %span#create_account_title #{t :accounts}
  = image_tag("loading.gif", :size => "16x16", :id => "loading", :style => "display: none;")
.remote#options{ hidden }
.remote#create_account{ hidden }

.list#accounts
  - if @accounts.any?
    = render @accounts
  - else
    = render "common/empty"

#paginate= render "common/paginate"
#export= render "common/export"

app/views/accounts/show.html.haml
= styles_for :task, :contact, :opportunity

#confirm{ hidden }
.title_tools#menu
  = link_to_inline(:edit_account, edit_account_path(@account), :text => t(:edit)) + " | "
  = link_to_function(t(:delete) + '?', confirm_delete(@account))
.title#edit_account_title= h(@account.name)

%div#edit_account{ hidden }

= render "comments/new", :commentable => @account
= render :partial => "common/timeline", :collection => @timeline

= hook(:show_account_bottom, self) do

  = section(@account, :tasks)
  .log#tasks
    = render "common/tasks"

  = section(@account, :contacts)
  .list#contacts
    - @contacts = @account.contacts.paginate(:page => 1, :per_page => 20)
    = render :partial => "contacts/contact", :collection => @contacts
  = will_paginate @contacts, :id => true, :params => {:action => :contacts}

  %br( style="clear:both" )

  = section(@account, :opportunities)
  .list#opportunities
    - @opportunities = @account.opportunities.paginate(:page => 1, :per_page => 20)
    = render :partial => "opportunities/opportunity", :collection => @opportunities
  = will_paginate @opportunities, :id => true, :params => {:action => :opportunities}

  = load_select_popups_for(@account, :tasks, :contacts, :opportunities)